#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "game.h"


/*
char *get_str(char *str, char *prefix, int hasQuotes){
    unsigned int i;
    for(i = 0; i < strlen(str) && i < strlen(prefix), str[i] == prefix[i]; i ++);
    if(i == strlen(str)){
        //implies sucess
        if(hasQuotes && str[i] == '"'){
            //has a quote in it
            char newStr[strlen(str)];
            unsigned int j;
            for(j = 0; str[j + i + 1] != '"' && str[j + i + 1] != '\0'; j++){
                newStr[j] = str[j + i + 1];
            }
            newStr[j] = '\0';
            return newStr;
        }else{
            return str + i;
        }
    }else{
        //implies failure
        return NULL;
    }
}*/

int hasWhiteSpace(char *str){
    for(unsigned int i = 0; i < strlen(str); i ++){
        if(isspace(str[i])) return 1;
    }
    return 0;
}

int main(int argc, char **argv){
    char name[MAX_INV_NAME];
    char plName[MAX_INV_NAME];
    char codeName[64];
    char description[MAX_INV_NAME];

    printf("enter race name: ");
    while(scanf("%s", name) == 0);

    printf("enter race plural name: ");
    while(scanf("%s", plName) == 0);

    printf("enter descripton: ");
    while(scanf("%s", description) == 0);

    printf("enter code name: ");
    while(scanf("%s", codeName) == 0 || hasWhiteSpace(codeName)){
        printf("enter code name (no spaces): ");
    }

    FILE *racec = fopen("race.c", "a");
    fseek(racec, 0, SEEK_END);
    fprintf(racec,"\n\n\\\\Generated by %s\nRace *gl_race_%s = NULL;\n\n",argv[0],codeName);
    fprintf(racec, "Race *race_%s(void){\n\tif(gl_race_%s){\n\t\treturn gl_race_%s;\n\t}else{\n\t\tgl_race_%s = make_race(%s,%s,%s);\n\t\treturn gl_race_%s;\n\t}}\n",
        codeName, codeName, codeName, codeName, name, plName, description, codeName);
    fclose(racec);

    FILE *racef = fopen("race.h", "a");
    fseek(racef, 0, SEEK_END);
    fprintf(racef,"\n\n\\\\Generated by %s\n",argv[0]);
    fprintf(racef,"Race *race_%s(void);\n\n",name);
    fclose(racef);
    return EXIT_SUCCESS;
}
