#include "game.h"

Race *find_race(char *name);

Race *race_human(void);
extern Race *gl_race_human;

Race *race_voidwretch(void);
extern Race *gl_race_voidwretch;

Race *race_kaskeer(void);
extern Race *gl_race_kaskeer;

Race *race_cavegolem(void);
extern Race *gl_race_cavegolem;

//Generated by ./make_race
Race *race_dwarf(void);
extern Race *gl_race_dwarf;

//Generated by ./make_race
Race *race_undead(void);
extern Race *gl_race_undead;


//Generated by ./make_race
Race *race_test(void);
extern Race *gl_race_test;

