#include "game.h"
#include "race.h"
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>


Race *make_race(char *name, char *plName, char *desc){
    Race *r = malloc(sizeof(Race));
    assert(r);
    strncpy(r->name, name, MAX_INV_NAME);
    strncpy(r->plName, plName, MAX_INV_NAME);
    strncpy(r->desc, desc, MAX_INV_DESC);
    return r;
}

int same_race(Race *race, char *name){
    if(verbose) printf("testing %s against %s\n", race->name, name);
    if(race == NULL) return 0;
    return strcmp(name,race->name) == 0;
}

Race *find_race(char *name){
    if(verbose) printf("trying to find %s\n",name);
    if(name == NULL) return NULL;

    //generated by ./make_race
	if(same_race(gl_race_test, name)) return gl_race_test;

    if(same_race(gl_race_voidwretch, name)) return gl_race_voidwretch;
    if(same_race(gl_race_kaskeer, name)) return gl_race_kaskeer;
    if(same_race(gl_race_undead, name)) return gl_race_undead;
    if(same_race(gl_race_dwarf, name)) return gl_race_dwarf;
    if(same_race(gl_race_cavegolem, name)) return gl_race_cavegolem;
    if(verbose) printf("could not find race matching, returning null\n");
    return NULL;
}

Race *gl_race_human = NULL;

Race *race_human(void){
    if(gl_race_human){
        return gl_race_human;
    }else{
        gl_race_human = make_race("human", "humans",
                "Mostly consisting of workers and farmers, humans are commonly found throughout the land");
        return gl_race_human;
    }
}

Race *gl_race_voidwretch = NULL;

Race *race_voidwretch(void){
    if(gl_race_voidwretch){
        return gl_race_voidwretch;
    }else{
        gl_race_voidwretch = make_race("void wretch", "void wretches",
                "A horrific underground creature that has mastered human speech. Known for forcing those unlucky enough to encounter one to solve a riddle to pass");
        return gl_race_voidwretch;
    }
}

Race *gl_race_kaskeer = NULL;

Race *race_kaskeer(void){
    if(gl_race_kaskeer){
        return gl_race_kaskeer;
    }else{
        gl_race_kaskeer = make_race("kaskeer", "kaskeers",
                "A large rat like creature with no eyes but an acute sense of smell.");
        return gl_race_kaskeer;
    }
}

Race *gl_race_cavegolem = NULL;

Race *race_cavegolem(void){
    if(gl_race_cavegolem){
        return gl_race_cavegolem;
    }else{
        gl_race_cavegolem = make_race("cave golem", "cave golems",
                "First raised by dark magicians eons ago, cave golems can now be found in some of the deeper cave systems");
        return gl_race_cavegolem;
    }
}

//Generated by ./make_race
Race *gl_race_dwarf = NULL;

Race *race_dwarf(void){
	if(gl_race_dwarf){
		return gl_race_dwarf;
	}else{
		gl_race_dwarf = make_race("dwarf","dwarves","a hardy mountain people, they are suspicious of humans and usually armed well");
		return gl_race_dwarf;
	}
}


//Generated by ./make_race
Race *gl_race_undead = NULL;

Race *race_undead(void){
	if(gl_race_undead){
		return gl_race_undead;
	}else{
		gl_race_undead = make_race("undead","undead","creatures risen from beings that once lived. Often urecognisable, they are now known only as the undead");
		return gl_race_undead;
	}
}


//Generated by ./make_race
Race *gl_race_test = NULL;

Race *race_test(void){
	if(gl_race_test){
		return gl_race_test;
	}else{
		gl_race_test = make_race("test","tests","testers");
		return gl_race_test;
	}
}
